config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "kittens#index"
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController

  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end

  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:notice] = "New kitten created"
      redirect_to @kitten
    else
      render :new, status: :unprocessable_entity
    end 

  end

  def new
    @kitten = Kitten.new
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
  end

  def update
    @kitten = Kitten.find(params[:id])

    if @kitten.update(kitten_params)
      flash[:alert] = "You have successfully changed your kitten"
      redirect_to @kitten
    else
      render :edit, status: :unprocessable_entity
    end

  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy
    redirect_to kittens_path, notice: 'Kitten successfully deleted'
  end

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: @kitten do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %> <br>

  <%= form.label :age %>
  <%= form.text_field :age %> <br>

  <%= form.label :cuteness %>
  <%= form.text_field :cuteness %> <br>

  <%= form.label :softness %>
  <%= form.text_field :softness %> <br>

  <%= form.submit %>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit Kitten</h1>
<%= render 'form' %>

app/views/kittens/index.html.erb
<h1>All Kittens</h1>
<div class="kitten-pics-container">
  <ul>
    <% @kittens.each do |kitten| %>
      <li>
        <div class='kitten-info-section'>
          <h4>Kitten Name: <%= kitten.name %></h4>
          <h4>Age: <%= kitten.age %></h4>
          <h4>Cuteness: <%= kitten.cuteness %></h4>
          <h4>Softness: <%= kitten.softness %></h4>
          <%= link_to "Go to kitten", kitten_path(kitten) %><br>
          <%= link_to "Delete kitten", kitten_path(kitten), data: { turbo_method: "delete" } %>
        </div>
      </li>
      <% end %>
  </ul>
</div>

<%= link_to "Create new kitten", new_kitten_path %>

app/views/kittens/new.html.erb
<h1>Create new kitten</h1>
<%= render 'form' %>

app/views/kittens/show.html.erb
<h1>Kitten Name: <%= @kitten.name %></h1>
<h4>Age: <%= @kitten.age %></h4>
<h4>Cuteness: <%= @kitten.cuteness %></h4>
<h4>Softness: <%= @kitten.softness %></h4>  
<%= link_to 'Edit', edit_kitten_path(@kitten) %>
<%= link_to 'Delete', kitten_path(@kitten), data: { turbo_method: "delete" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |name, message| %>
      <p class="<%= name %>"><%= message %></p>
    <% end %>
    <%= yield %>
  </body>
</html>